version: '3.8'

services:
  # MongoDB 데이터베이스
  mongodb:
    image: mongo:7.0
    container_name: kkalkalnews_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: kkalkalnews
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - kkalkalnews_network

  # 뉴스 API 애플리케이션
  news-api:
    build: .
    container_name: kkalkalnews_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # MongoDB 설정
      USE_MONGODB: "true"
      MONGODB_URI: "mongodb://newsuser:newspass@mongodb:27017/kkalkalnews"
      
      # AI API 키 (환경변수에서 가져오기)
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      AI_PROVIDER: "openai"
      
      # 보안 설정
      INTERNAL_API_KEY: "${INTERNAL_API_KEY:-your-secret-api-key-here}"
      
      # 애플리케이션 설정
      ENVIRONMENT: "production"
      DEBUG: "false"
      
      # CORS 설정 (모바일 접근 허용)
      CORS_ORIGINS: "*"
      
    depends_on:
      - mongodb
    networks:
      - kkalkalnews_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/system/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Nginx 리버스 프록시 (선택사항)
  nginx:
    image: nginx:alpine
    container_name: kkalkalnews_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl/certs:ro
    depends_on:
      - news-api
    networks:
      - kkalkalnews_network

volumes:
  mongodb_data:

networks:
  kkalkalnews_network:
    driver: bridge